# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4da5d66eb6e3146a8bc4f23745243dcdf63cc7c63c83e10ef362bd6249891a0bc4521f2fa10153aebca72ab0f624b3862d8dc2c205c0b17fdf664ef87025836b

test:
  secret_key_base: aa3ed7c6c03c331e03c99c784411e0189f411c63b34c7dc849cb1234f0ba6c9074a90b829f6c4e0b20c0efd968748ec9bafe6c3e7c7af0d17ca1d005ae010c5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
